defaults: &defaults
  admin_email: "yinan.wu@ycshell.com"
  app_domain: "www.ycshell.com"
  app_email: "redstar_wjxt@ycshell.com"
  app_port: "80"
  smtp_address: "smtp.sohu.com"
  smtp_port: 25
  smtp_domain: "sohu.com"
  smtp_user_name: "redstar_wjxt"
  smtp_password: "Pass123"

development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults

