defaults: &defaults
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  database: db/shell_development.sqlite3
  <<: *defaults
test:
  database: db/shell_test.sqlite3
  <<: *defaults
production:
  database: db/shell_production.sqlite3
  <<: *defaults